### ISSUE TITLE
json files

### ISSUE THREAD

**Issue by SHMCU** [mahmoudnafifi/C5#1]
Is there a sample json file so I can generate json files for new data?

Thanks,
Simon

**Comment by mahmoudnafifi** [comment]
You can store the ground-truth illuminant color of each image in a JSON file with a key named either `illuminant_color_raw` or `gt_ill`. This JSON file should be named with the same name of the corresponding image and ends with '_metadata.json' postfix. 

I uploaded an example in this [link](https://github.com/mahmoudnafifi/C5/files/6360589/cube_test_006_sensorname_canon_eos_550d_metadata.zip).
