### ISSUE TITLE
about preprocessing of the input image

### ISSUE THREAD

**Issue by SHMCU** [mahmoudnafifi/C5#3]
Hi Mahmoud,

Thanks for sharing the great work! 
May I know whether there is some preprocessing to the images input to the network. Here is what I observed, when the input is from the ffcc's dataset: https://github.com/google/ffcc/tree/master/data
the output looks good. But if input other data like NUS from here: http://cvil.eecs.yorku.ca/projects/public_html/illuminant/illuminant.html
the output is bad. Is this because I missed some preprocessing steps?

Thanks
Simon

**Comment by mahmoudnafifi** [comment]
Hi Simon,

Yes, the image should be normalized using the black-level and saturation-level values. You can either find these values in the DNG metadata or from the dataset provider (for example in the [NUS](http://cvil.eecs.yorku.ca/projects/public_html/illuminant/illuminant.html) dataset those values are given from each camera). Then, each image should be normalized as follows: normalized_image =  (image - black_level) / (saturation_level - black_level)

I hope this helps.
